name: serve_dynamic_ui
description: A Flutter plugin to render dynamic widgets based on server driven ui.
version: 1.0.0
homepage: https://github.com/Arunshaik2001/serve_dynamic_ui
topics:
  - dynamic-widgets
  - server-driven-ui
  - backend-driven-ui

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.8.1
  dio: ^5.2.1+1
  scroll_to_index: ^3.0.1
  simple_html_css: ^5.0.0
  shimmer: ^3.0.0
  floor: ^1.4.2
  crypto: ^3.0.3
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.2
  carousel_slider: ^4.2.1
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.1
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.6.2
  build_runner: ^2.4.6
  floor_generator: ^1.4.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
